// svelte-bootstrap-app/src/lib/Footer.svelte
<script>
  import Icon from "svelte-icons-pack/Icon.svelte";
  import VscGithub from "svelte-icons-pack/vsc/VscGithub";
</script>

<footer class="fixed-bottom left-10">
  <a
    href="https://github.com/201flaviosilva-labs/Expense-Trackers"
    target="_blank"
    rel="noreferrer"
    class="ml-8 mb-8"
  >
    <Icon src={VscGithub} color="white" size="2em" />
  </a>
</footer>

// react-app/src/components/Footer/index.jsx
import { GoMarkGithub } from "react-icons/go";
import styles from "./style.module.scss";

export default function Footer() {
	return (
		<footer className={styles.footer}>
			<a
				href="https://github.com/201flaviosilva-labs/Expense-Trackers"
				target="_blank"
				rel="noreferrer"
			>
				<GoMarkGithub size={32} />
			</a>
		</footer>
	)
}
