// svelte-bootstrap-app/src/lib/Header.svelte
<script>
  import {
    Collapse,
    Form,
    FormGroup,
    Input,
    Nav,
    NavItem,
    Navbar,
    NavbarBrand,
    NavbarToggler,
  } from "sveltestrap";

  export let searchTransaction;
  function handleChangeSearch(event) {
    searchTransaction = event.target.value;
  }

  let isNavOpen = false;
  function toggleNavbar(event) {
    isNavOpen = event.detail.isOpen;
  }
</script>

<header>
  <Navbar color="dark" dark expand="sm">
    <NavbarBrand href="/">Expense Tracker Svelte Bootstrap App</NavbarBrand>
    <NavbarToggler on:click={() => (isNavOpen = !isNavOpen)} />

    <Collapse isOpen={isNavOpen} navbar expand="sm" on:update={toggleNavbar}>
      <Nav class="ms-auto" navbar>
        <NavItem>
          <Form>
            <FormGroup>
              <Input
                color="dark"
                placeholder="Search for a transaction"
                value={searchTransaction}
                on:input={handleChangeSearch}
              />
            </FormGroup>
          </Form>
        </NavItem>
      </Nav>
    </Collapse>
  </Navbar>
</header>

<style lang="scss">
  header {
    width: 100vw;
  }
</style>

// react-app/src/components/Header/index.jsx
import Input from "../Input";
import styles from "./style.module.scss";

export default function Header({ searchTransaction, setSearchTransaction }) {
	return (
		<header className={styles.header}>
			<h1>Expense Tracker</h1>
			<Input
				placeholder="Search for a transaction"
				value={searchTransaction}
				setValue={setSearchTransaction}
			/>
			<h1>React App</h1>
		</header>
	)
}
