// svelte-bootstrap-app/src/lib/Balance.svelte
<script>
  import BiLineChart from "svelte-icons-pack/bi/BiLineChart";
  import BiLineChartDown from "svelte-icons-pack/bi/BiLineChartDown";
  import FaSolidBalanceScale from "svelte-icons-pack/fa/FaSolidBalanceScale";
  import { Container, Row } from "sveltestrap";
  import { getColorByAmount } from "../utils";
  import BalanceCard from "./BalanceCard.svelte";

  export let transactionsList;
  let income = 0;
  let expense = 0;

  $: {
    income = transactionsList.reduce(
      (acc, cur) => (cur.amount > 0 ? acc + Number(cur.amount) : acc),
      0
    );
    expense = transactionsList.reduce(
      (acc, cur) => (cur.amount < 0 ? acc + Number(cur.amount) : acc),
      0
    );
  }
</script>

<Container class="mb-3">
  <Row>
    <BalanceCard
      color="success"
      title="Total Incomes"
      iconSrc={BiLineChart}
      amount={income}
    />

    <BalanceCard
      color={getColorByAmount(income + expense)}
      title="Total Balance"
      iconSrc={FaSolidBalanceScale}
      amount={income + expense}
    />

    <BalanceCard
      color="danger"
      title="Total Expenses"
      iconSrc={BiLineChartDown}
      amount={expense}
    />
  </Row>
</Container>

// react-app/src/components/Main/Balance.jsx
import styles from "./style.module.scss";

export default function Balance({ transactions }) {
	const income = transactions.reduce((acc, cur) => cur.amount > 0 ? acc + Number(cur.amount) : acc, 0);
	const expense = transactions.reduce((acc, cur) => cur.amount < 0 ? acc + Number(cur.amount) : acc, 0);

	return (
		<div className={styles.balance}>
			<h2>Balance</h2>

			<div>
				<Column label="Income" value={income} />
				<Column label="Total" value={income + expense} />
				<Column label="Expense" value={expense} />
			</div>
		</div>
	)
}

function Column({ label, value }) {
	return (
		<div>
			<p>{label}</p>
			<p>{value}€</p>
		</div>
	)

}
